apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: hello-listener
spec:
  resources:
    kubernetesResource:
      serviceType: LoadBalancer
  serviceAccountName: tekton-robot
  triggers:
    - name: hello-trigger
      interceptors:
      - github:
          eventTypes:
          - push
      - cel:
          filter: >-
            "body.ref == 'refs/heads/main'"
      bindings:
      - ref: hello-binding
      template:
        ref: hello-template
