apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: cd-listener
  namespace: tekton-demo
spec:
  resources:
    kubernetesResource:
      serviceType: LoadBalancer
  serviceAccountName: triggers-sa
  triggers:
    - name: dev-trigger
      interceptors:
      - name: "validate GitHub payload and filter on eventType + branch"
        ref:
          name: "github"
        params:
        - name: "secretRef"
          value:
            secretName: cd-secret
            secretKey: secretToken
        - name: "eventTypes"
          value: ["push"]
      - name: "CEL filter: check for correct branch"
        ref:
          name: "cel"
        params:
        - name: "filter"
          value: "body.ref == 'refs/heads/dev'"
      bindings:
      - ref: dev-binding
      template:
        ref: dev-template
    - name: live-trigger
      interceptors:
      - name: "validate GitHub payload and filter on eventType + action"
        ref:
          name: "github"
        params:
        - name: "secretRef"
          value:
            secretName: cd-secret
            secretKey: secretToken
        - name: "eventTypes"
          value: ["pull_request"]
      - name: "CEL filter: check for correct branch"
        ref:
          name: "cel"
        params:
        - name: "filter"
          value: "body.action == 'closed'"
      bindings:
      - ref: live-binding
      template:
        ref: live-template
