apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: dev-pipeline
  namespace: tekton-demo
spec:
  params:
  - name: repoUrl
    type: string
  - name: pusher
    type: string
  tasks:
    - name: dev-logger
      taskRef:
        name: dev-logger
      params:
      - name: repoUrl
        value: $(params.repoUrl)
      - name: pusher
        value: $(params.pusher)
