apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: dev-pipeline
  namespace: tekton-demo
spec:
  params:
  - name: repoUrl
    type: string
  - name: pusher
    type: string
  - name: package
    type: string
  workspaces: 
  - name: shared-data
    description: This workspace contains the cloned repo files, so they can be read by the next task.
  tasks:
    - name: dev-logger
      taskRef:
        name: dev-logger
      params:
      - name: repoUrl
        value: $(params.repoUrl)
      - name: pusher
        value: $(params.pusher)
    - name: clone
      taskRef:
        name: git-clone
      workspaces:
      - name: output
        workspace: shared-data
      params:
      - name: url
        value: $(params.repoUrl) # this should be the url of the dev
    - name: lint
      runAfter: [clone]
      taskRef:
        name: golangci-lint
      workspaces:
      - name: source
        workspace: shared-data
      params:
      - name: package
        value: $(params.package)
      - name: flags
        value: --verbose

