apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: dev-template
  namespace: tekton-demo
spec:
  params:
  - name: repoUrl
    default: "REPOURL_NOT_FOUND"
  - name: pusher
    default: "PUSHER_NOT_FOUND"
  - name: package
    default: github.com/danielraso7/cloud-computing-project-demoapp/tree/dev
  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      generateName: dev-pipeline-
    spec:
      pipelineRef:
        name: dev-pipeline
      podTemplate:
        securityContext:
          fsGroup: 65532
      workspaces:
      - name: shared-data
        volumeClaimTemplate:
          spec:
            accessModes:
            - ReadWriteOnce
            resources:
              requests:
                storage: 1Gi
      params:
      - name: repoUrl
        value: $(tt.params.repoUrl)
      - name: pusher
        value: $(tt.params.pusher)
      - name: package
        value: $(tt.params.package)
